// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FightMsg.proto

package xn.protobuf.fight;

public final class FightMsg {
  private FightMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FightSinglePVEReqMsg_6101OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    int getId();
  }
  /**
   * Protobuf type {@code FightSinglePVEReqMsg_6101}
   *
   * <pre>
   *请求pve战斗
   * </pre>
   */
  public static final class FightSinglePVEReqMsg_6101 extends
      com.google.protobuf.GeneratedMessage
      implements FightSinglePVEReqMsg_6101OrBuilder {
    // Use FightSinglePVEReqMsg_6101.newBuilder() to construct.
    private FightSinglePVEReqMsg_6101(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FightSinglePVEReqMsg_6101(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FightSinglePVEReqMsg_6101 defaultInstance;
    public static FightSinglePVEReqMsg_6101 getDefaultInstance() {
      return defaultInstance;
    }

    public FightSinglePVEReqMsg_6101 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FightSinglePVEReqMsg_6101(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEReqMsg_6101_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEReqMsg_6101_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101.class, xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101.Builder.class);
    }

    public static com.google.protobuf.Parser<FightSinglePVEReqMsg_6101> PARSER =
        new com.google.protobuf.AbstractParser<FightSinglePVEReqMsg_6101>() {
      public FightSinglePVEReqMsg_6101 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FightSinglePVEReqMsg_6101(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FightSinglePVEReqMsg_6101> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FightSinglePVEReqMsg_6101}
     *
     * <pre>
     *请求pve战斗
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEReqMsg_6101_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEReqMsg_6101_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101.class, xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101.Builder.class);
      }

      // Construct using xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEReqMsg_6101_descriptor;
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 getDefaultInstanceForType() {
        return xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101.getDefaultInstance();
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 build() {
        xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 buildPartial() {
        xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 result = new xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101) {
          return mergeFrom((xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 other) {
        if (other == xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.fight.FightMsg.FightSinglePVEReqMsg_6101) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FightSinglePVEReqMsg_6101)
    }

    static {
      defaultInstance = new FightSinglePVEReqMsg_6101(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FightSinglePVEReqMsg_6101)
  }

  public interface FightSinglePVEResMsg_6102OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 reulst = 1;
    /**
     * <code>optional int32 reulst = 1;</code>
     *
     * <pre>
     *1进入战斗 2怪物战斗中 3怪物不存在
     * </pre>
     */
    boolean hasReulst();
    /**
     * <code>optional int32 reulst = 1;</code>
     *
     * <pre>
     *1进入战斗 2怪物战斗中 3怪物不存在
     * </pre>
     */
    int getReulst();

    // optional int32 id = 2;
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    int getId();
  }
  /**
   * Protobuf type {@code FightSinglePVEResMsg_6102}
   *
   * <pre>
   *返回请求pev战斗结果
   * </pre>
   */
  public static final class FightSinglePVEResMsg_6102 extends
      com.google.protobuf.GeneratedMessage
      implements FightSinglePVEResMsg_6102OrBuilder {
    // Use FightSinglePVEResMsg_6102.newBuilder() to construct.
    private FightSinglePVEResMsg_6102(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FightSinglePVEResMsg_6102(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FightSinglePVEResMsg_6102 defaultInstance;
    public static FightSinglePVEResMsg_6102 getDefaultInstance() {
      return defaultInstance;
    }

    public FightSinglePVEResMsg_6102 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FightSinglePVEResMsg_6102(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              reulst_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResMsg_6102_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResMsg_6102_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102.class, xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102.Builder.class);
    }

    public static com.google.protobuf.Parser<FightSinglePVEResMsg_6102> PARSER =
        new com.google.protobuf.AbstractParser<FightSinglePVEResMsg_6102>() {
      public FightSinglePVEResMsg_6102 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FightSinglePVEResMsg_6102(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FightSinglePVEResMsg_6102> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 reulst = 1;
    public static final int REULST_FIELD_NUMBER = 1;
    private int reulst_;
    /**
     * <code>optional int32 reulst = 1;</code>
     *
     * <pre>
     *1进入战斗 2怪物战斗中 3怪物不存在
     * </pre>
     */
    public boolean hasReulst() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 reulst = 1;</code>
     *
     * <pre>
     *1进入战斗 2怪物战斗中 3怪物不存在
     * </pre>
     */
    public int getReulst() {
      return reulst_;
    }

    // optional int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      reulst_ = 0;
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, reulst_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, reulst_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FightSinglePVEResMsg_6102}
     *
     * <pre>
     *返回请求pev战斗结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResMsg_6102_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResMsg_6102_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102.class, xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102.Builder.class);
      }

      // Construct using xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reulst_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResMsg_6102_descriptor;
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 getDefaultInstanceForType() {
        return xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102.getDefaultInstance();
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 build() {
        xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 buildPartial() {
        xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 result = new xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reulst_ = reulst_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102) {
          return mergeFrom((xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 other) {
        if (other == xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102.getDefaultInstance()) return this;
        if (other.hasReulst()) {
          setReulst(other.getReulst());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.fight.FightMsg.FightSinglePVEResMsg_6102) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 reulst = 1;
      private int reulst_ ;
      /**
       * <code>optional int32 reulst = 1;</code>
       *
       * <pre>
       *1进入战斗 2怪物战斗中 3怪物不存在
       * </pre>
       */
      public boolean hasReulst() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 reulst = 1;</code>
       *
       * <pre>
       *1进入战斗 2怪物战斗中 3怪物不存在
       * </pre>
       */
      public int getReulst() {
        return reulst_;
      }
      /**
       * <code>optional int32 reulst = 1;</code>
       *
       * <pre>
       *1进入战斗 2怪物战斗中 3怪物不存在
       * </pre>
       */
      public Builder setReulst(int value) {
        bitField0_ |= 0x00000001;
        reulst_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 reulst = 1;</code>
       *
       * <pre>
       *1进入战斗 2怪物战斗中 3怪物不存在
       * </pre>
       */
      public Builder clearReulst() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reulst_ = 0;
        onChanged();
        return this;
      }

      // optional int32 id = 2;
      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FightSinglePVEResMsg_6102)
    }

    static {
      defaultInstance = new FightSinglePVEResMsg_6102(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FightSinglePVEResMsg_6102)
  }

  public interface FightSinglePVEResultReqMsg_6103OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string report = 1;
    /**
     * <code>optional string report = 1;</code>
     *
     * <pre>
     *战斗过程(战报)
     * </pre>
     */
    boolean hasReport();
    /**
     * <code>optional string report = 1;</code>
     *
     * <pre>
     *战斗过程(战报)
     * </pre>
     */
    java.lang.String getReport();
    /**
     * <code>optional string report = 1;</code>
     *
     * <pre>
     *战斗过程(战报)
     * </pre>
     */
    com.google.protobuf.ByteString
        getReportBytes();

    // optional int32 id = 2;
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    int getId();

    // optional int32 result = 3;
    /**
     * <code>optional int32 result = 3;</code>
     *
     * <pre>
     *战斗结果  1胜利 -1失败 0平局(测试阶段使用，正式还是需要解析战报内容)
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional int32 result = 3;</code>
     *
     * <pre>
     *战斗结果  1胜利 -1失败 0平局(测试阶段使用，正式还是需要解析战报内容)
     * </pre>
     */
    int getResult();
  }
  /**
   * Protobuf type {@code FightSinglePVEResultReqMsg_6103}
   *
   * <pre>
   *发送单人pve战斗结果
   * </pre>
   */
  public static final class FightSinglePVEResultReqMsg_6103 extends
      com.google.protobuf.GeneratedMessage
      implements FightSinglePVEResultReqMsg_6103OrBuilder {
    // Use FightSinglePVEResultReqMsg_6103.newBuilder() to construct.
    private FightSinglePVEResultReqMsg_6103(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FightSinglePVEResultReqMsg_6103(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FightSinglePVEResultReqMsg_6103 defaultInstance;
    public static FightSinglePVEResultReqMsg_6103 getDefaultInstance() {
      return defaultInstance;
    }

    public FightSinglePVEResultReqMsg_6103 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FightSinglePVEResultReqMsg_6103(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              report_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              result_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResultReqMsg_6103_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResultReqMsg_6103_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103.class, xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103.Builder.class);
    }

    public static com.google.protobuf.Parser<FightSinglePVEResultReqMsg_6103> PARSER =
        new com.google.protobuf.AbstractParser<FightSinglePVEResultReqMsg_6103>() {
      public FightSinglePVEResultReqMsg_6103 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FightSinglePVEResultReqMsg_6103(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FightSinglePVEResultReqMsg_6103> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string report = 1;
    public static final int REPORT_FIELD_NUMBER = 1;
    private java.lang.Object report_;
    /**
     * <code>optional string report = 1;</code>
     *
     * <pre>
     *战斗过程(战报)
     * </pre>
     */
    public boolean hasReport() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string report = 1;</code>
     *
     * <pre>
     *战斗过程(战报)
     * </pre>
     */
    public java.lang.String getReport() {
      java.lang.Object ref = report_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          report_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string report = 1;</code>
     *
     * <pre>
     *战斗过程(战报)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReportBytes() {
      java.lang.Object ref = report_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        report_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     *怪物唯一id
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // optional int32 result = 3;
    public static final int RESULT_FIELD_NUMBER = 3;
    private int result_;
    /**
     * <code>optional int32 result = 3;</code>
     *
     * <pre>
     *战斗结果  1胜利 -1失败 0平局(测试阶段使用，正式还是需要解析战报内容)
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 result = 3;</code>
     *
     * <pre>
     *战斗结果  1胜利 -1失败 0平局(测试阶段使用，正式还是需要解析战报内容)
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    private void initFields() {
      report_ = "";
      id_ = 0;
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getReportBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getReportBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FightSinglePVEResultReqMsg_6103}
     *
     * <pre>
     *发送单人pve战斗结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResultReqMsg_6103_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResultReqMsg_6103_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103.class, xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103.Builder.class);
      }

      // Construct using xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        report_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResultReqMsg_6103_descriptor;
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 getDefaultInstanceForType() {
        return xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103.getDefaultInstance();
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 build() {
        xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 buildPartial() {
        xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 result = new xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.report_ = report_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103) {
          return mergeFrom((xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 other) {
        if (other == xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103.getDefaultInstance()) return this;
        if (other.hasReport()) {
          bitField0_ |= 0x00000001;
          report_ = other.report_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.fight.FightMsg.FightSinglePVEResultReqMsg_6103) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string report = 1;
      private java.lang.Object report_ = "";
      /**
       * <code>optional string report = 1;</code>
       *
       * <pre>
       *战斗过程(战报)
       * </pre>
       */
      public boolean hasReport() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string report = 1;</code>
       *
       * <pre>
       *战斗过程(战报)
       * </pre>
       */
      public java.lang.String getReport() {
        java.lang.Object ref = report_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          report_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string report = 1;</code>
       *
       * <pre>
       *战斗过程(战报)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReportBytes() {
        java.lang.Object ref = report_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          report_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string report = 1;</code>
       *
       * <pre>
       *战斗过程(战报)
       * </pre>
       */
      public Builder setReport(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        report_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string report = 1;</code>
       *
       * <pre>
       *战斗过程(战报)
       * </pre>
       */
      public Builder clearReport() {
        bitField0_ = (bitField0_ & ~0x00000001);
        report_ = getDefaultInstance().getReport();
        onChanged();
        return this;
      }
      /**
       * <code>optional string report = 1;</code>
       *
       * <pre>
       *战斗过程(战报)
       * </pre>
       */
      public Builder setReportBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        report_ = value;
        onChanged();
        return this;
      }

      // optional int32 id = 2;
      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       *怪物唯一id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional int32 result = 3;
      private int result_ ;
      /**
       * <code>optional int32 result = 3;</code>
       *
       * <pre>
       *战斗结果  1胜利 -1失败 0平局(测试阶段使用，正式还是需要解析战报内容)
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 result = 3;</code>
       *
       * <pre>
       *战斗结果  1胜利 -1失败 0平局(测试阶段使用，正式还是需要解析战报内容)
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional int32 result = 3;</code>
       *
       * <pre>
       *战斗结果  1胜利 -1失败 0平局(测试阶段使用，正式还是需要解析战报内容)
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000004;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result = 3;</code>
       *
       * <pre>
       *战斗结果  1胜利 -1失败 0平局(测试阶段使用，正式还是需要解析战报内容)
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000004);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FightSinglePVEResultReqMsg_6103)
    }

    static {
      defaultInstance = new FightSinglePVEResultReqMsg_6103(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FightSinglePVEResultReqMsg_6103)
  }

  public interface FightSinglePVEResultResMsg_6104OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 result = 1;
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *战斗结果  1胜利 -1失败 0平局
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *战斗结果  1胜利 -1失败 0平局
     * </pre>
     */
    int getResult();

    // repeated .AwardItemData dropList = 2;
    /**
     * <code>repeated .AwardItemData dropList = 2;</code>
     *
     * <pre>
     *掉落物品
     * </pre>
     */
    java.util.List<xn.protobuf.award.AwardMsg.AwardItemData> 
        getDropListList();
    /**
     * <code>repeated .AwardItemData dropList = 2;</code>
     *
     * <pre>
     *掉落物品
     * </pre>
     */
    xn.protobuf.award.AwardMsg.AwardItemData getDropList(int index);
    /**
     * <code>repeated .AwardItemData dropList = 2;</code>
     *
     * <pre>
     *掉落物品
     * </pre>
     */
    int getDropListCount();
    /**
     * <code>repeated .AwardItemData dropList = 2;</code>
     *
     * <pre>
     *掉落物品
     * </pre>
     */
    java.util.List<? extends xn.protobuf.award.AwardMsg.AwardItemDataOrBuilder> 
        getDropListOrBuilderList();
    /**
     * <code>repeated .AwardItemData dropList = 2;</code>
     *
     * <pre>
     *掉落物品
     * </pre>
     */
    xn.protobuf.award.AwardMsg.AwardItemDataOrBuilder getDropListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code FightSinglePVEResultResMsg_6104}
   *
   * <pre>
   *返回单人pve战斗结果
   * </pre>
   */
  public static final class FightSinglePVEResultResMsg_6104 extends
      com.google.protobuf.GeneratedMessage
      implements FightSinglePVEResultResMsg_6104OrBuilder {
    // Use FightSinglePVEResultResMsg_6104.newBuilder() to construct.
    private FightSinglePVEResultResMsg_6104(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FightSinglePVEResultResMsg_6104(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FightSinglePVEResultResMsg_6104 defaultInstance;
    public static FightSinglePVEResultResMsg_6104 getDefaultInstance() {
      return defaultInstance;
    }

    public FightSinglePVEResultResMsg_6104 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FightSinglePVEResultResMsg_6104(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                dropList_ = new java.util.ArrayList<xn.protobuf.award.AwardMsg.AwardItemData>();
                mutable_bitField0_ |= 0x00000002;
              }
              dropList_.add(input.readMessage(xn.protobuf.award.AwardMsg.AwardItemData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          dropList_ = java.util.Collections.unmodifiableList(dropList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResultResMsg_6104_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResultResMsg_6104_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104.class, xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104.Builder.class);
    }

    public static com.google.protobuf.Parser<FightSinglePVEResultResMsg_6104> PARSER =
        new com.google.protobuf.AbstractParser<FightSinglePVEResultResMsg_6104>() {
      public FightSinglePVEResultResMsg_6104 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FightSinglePVEResultResMsg_6104(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FightSinglePVEResultResMsg_6104> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *战斗结果  1胜利 -1失败 0平局
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *战斗结果  1胜利 -1失败 0平局
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    // repeated .AwardItemData dropList = 2;
    public static final int DROPLIST_FIELD_NUMBER = 2;
    private java.util.List<xn.protobuf.award.AwardMsg.AwardItemData> dropList_;
    /**
     * <code>repeated .AwardItemData dropList = 2;</code>
     *
     * <pre>
     *掉落物品
     * </pre>
     */
    public java.util.List<xn.protobuf.award.AwardMsg.AwardItemData> getDropListList() {
      return dropList_;
    }
    /**
     * <code>repeated .AwardItemData dropList = 2;</code>
     *
     * <pre>
     *掉落物品
     * </pre>
     */
    public java.util.List<? extends xn.protobuf.award.AwardMsg.AwardItemDataOrBuilder> 
        getDropListOrBuilderList() {
      return dropList_;
    }
    /**
     * <code>repeated .AwardItemData dropList = 2;</code>
     *
     * <pre>
     *掉落物品
     * </pre>
     */
    public int getDropListCount() {
      return dropList_.size();
    }
    /**
     * <code>repeated .AwardItemData dropList = 2;</code>
     *
     * <pre>
     *掉落物品
     * </pre>
     */
    public xn.protobuf.award.AwardMsg.AwardItemData getDropList(int index) {
      return dropList_.get(index);
    }
    /**
     * <code>repeated .AwardItemData dropList = 2;</code>
     *
     * <pre>
     *掉落物品
     * </pre>
     */
    public xn.protobuf.award.AwardMsg.AwardItemDataOrBuilder getDropListOrBuilder(
        int index) {
      return dropList_.get(index);
    }

    private void initFields() {
      result_ = 0;
      dropList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      for (int i = 0; i < dropList_.size(); i++) {
        output.writeMessage(2, dropList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      for (int i = 0; i < dropList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, dropList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FightSinglePVEResultResMsg_6104}
     *
     * <pre>
     *返回单人pve战斗结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResultResMsg_6104_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResultResMsg_6104_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104.class, xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104.Builder.class);
      }

      // Construct using xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDropListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (dropListBuilder_ == null) {
          dropList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          dropListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.fight.FightMsg.internal_static_FightSinglePVEResultResMsg_6104_descriptor;
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 getDefaultInstanceForType() {
        return xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104.getDefaultInstance();
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 build() {
        xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 buildPartial() {
        xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 result = new xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (dropListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            dropList_ = java.util.Collections.unmodifiableList(dropList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.dropList_ = dropList_;
        } else {
          result.dropList_ = dropListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104) {
          return mergeFrom((xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 other) {
        if (other == xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (dropListBuilder_ == null) {
          if (!other.dropList_.isEmpty()) {
            if (dropList_.isEmpty()) {
              dropList_ = other.dropList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDropListIsMutable();
              dropList_.addAll(other.dropList_);
            }
            onChanged();
          }
        } else {
          if (!other.dropList_.isEmpty()) {
            if (dropListBuilder_.isEmpty()) {
              dropListBuilder_.dispose();
              dropListBuilder_ = null;
              dropList_ = other.dropList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              dropListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDropListFieldBuilder() : null;
            } else {
              dropListBuilder_.addAllMessages(other.dropList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.fight.FightMsg.FightSinglePVEResultResMsg_6104) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 result = 1;
      private int result_ ;
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *战斗结果  1胜利 -1失败 0平局
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *战斗结果  1胜利 -1失败 0平局
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *战斗结果  1胜利 -1失败 0平局
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *战斗结果  1胜利 -1失败 0平局
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // repeated .AwardItemData dropList = 2;
      private java.util.List<xn.protobuf.award.AwardMsg.AwardItemData> dropList_ =
        java.util.Collections.emptyList();
      private void ensureDropListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          dropList_ = new java.util.ArrayList<xn.protobuf.award.AwardMsg.AwardItemData>(dropList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          xn.protobuf.award.AwardMsg.AwardItemData, xn.protobuf.award.AwardMsg.AwardItemData.Builder, xn.protobuf.award.AwardMsg.AwardItemDataOrBuilder> dropListBuilder_;

      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public java.util.List<xn.protobuf.award.AwardMsg.AwardItemData> getDropListList() {
        if (dropListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dropList_);
        } else {
          return dropListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public int getDropListCount() {
        if (dropListBuilder_ == null) {
          return dropList_.size();
        } else {
          return dropListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public xn.protobuf.award.AwardMsg.AwardItemData getDropList(int index) {
        if (dropListBuilder_ == null) {
          return dropList_.get(index);
        } else {
          return dropListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public Builder setDropList(
          int index, xn.protobuf.award.AwardMsg.AwardItemData value) {
        if (dropListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDropListIsMutable();
          dropList_.set(index, value);
          onChanged();
        } else {
          dropListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public Builder setDropList(
          int index, xn.protobuf.award.AwardMsg.AwardItemData.Builder builderForValue) {
        if (dropListBuilder_ == null) {
          ensureDropListIsMutable();
          dropList_.set(index, builderForValue.build());
          onChanged();
        } else {
          dropListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public Builder addDropList(xn.protobuf.award.AwardMsg.AwardItemData value) {
        if (dropListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDropListIsMutable();
          dropList_.add(value);
          onChanged();
        } else {
          dropListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public Builder addDropList(
          int index, xn.protobuf.award.AwardMsg.AwardItemData value) {
        if (dropListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDropListIsMutable();
          dropList_.add(index, value);
          onChanged();
        } else {
          dropListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public Builder addDropList(
          xn.protobuf.award.AwardMsg.AwardItemData.Builder builderForValue) {
        if (dropListBuilder_ == null) {
          ensureDropListIsMutable();
          dropList_.add(builderForValue.build());
          onChanged();
        } else {
          dropListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public Builder addDropList(
          int index, xn.protobuf.award.AwardMsg.AwardItemData.Builder builderForValue) {
        if (dropListBuilder_ == null) {
          ensureDropListIsMutable();
          dropList_.add(index, builderForValue.build());
          onChanged();
        } else {
          dropListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public Builder addAllDropList(
          java.lang.Iterable<? extends xn.protobuf.award.AwardMsg.AwardItemData> values) {
        if (dropListBuilder_ == null) {
          ensureDropListIsMutable();
          super.addAll(values, dropList_);
          onChanged();
        } else {
          dropListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public Builder clearDropList() {
        if (dropListBuilder_ == null) {
          dropList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          dropListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public Builder removeDropList(int index) {
        if (dropListBuilder_ == null) {
          ensureDropListIsMutable();
          dropList_.remove(index);
          onChanged();
        } else {
          dropListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public xn.protobuf.award.AwardMsg.AwardItemData.Builder getDropListBuilder(
          int index) {
        return getDropListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public xn.protobuf.award.AwardMsg.AwardItemDataOrBuilder getDropListOrBuilder(
          int index) {
        if (dropListBuilder_ == null) {
          return dropList_.get(index);  } else {
          return dropListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public java.util.List<? extends xn.protobuf.award.AwardMsg.AwardItemDataOrBuilder> 
           getDropListOrBuilderList() {
        if (dropListBuilder_ != null) {
          return dropListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dropList_);
        }
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public xn.protobuf.award.AwardMsg.AwardItemData.Builder addDropListBuilder() {
        return getDropListFieldBuilder().addBuilder(
            xn.protobuf.award.AwardMsg.AwardItemData.getDefaultInstance());
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public xn.protobuf.award.AwardMsg.AwardItemData.Builder addDropListBuilder(
          int index) {
        return getDropListFieldBuilder().addBuilder(
            index, xn.protobuf.award.AwardMsg.AwardItemData.getDefaultInstance());
      }
      /**
       * <code>repeated .AwardItemData dropList = 2;</code>
       *
       * <pre>
       *掉落物品
       * </pre>
       */
      public java.util.List<xn.protobuf.award.AwardMsg.AwardItemData.Builder> 
           getDropListBuilderList() {
        return getDropListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          xn.protobuf.award.AwardMsg.AwardItemData, xn.protobuf.award.AwardMsg.AwardItemData.Builder, xn.protobuf.award.AwardMsg.AwardItemDataOrBuilder> 
          getDropListFieldBuilder() {
        if (dropListBuilder_ == null) {
          dropListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              xn.protobuf.award.AwardMsg.AwardItemData, xn.protobuf.award.AwardMsg.AwardItemData.Builder, xn.protobuf.award.AwardMsg.AwardItemDataOrBuilder>(
                  dropList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          dropList_ = null;
        }
        return dropListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:FightSinglePVEResultResMsg_6104)
    }

    static {
      defaultInstance = new FightSinglePVEResultResMsg_6104(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FightSinglePVEResultResMsg_6104)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FightSinglePVEReqMsg_6101_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FightSinglePVEReqMsg_6101_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FightSinglePVEResMsg_6102_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FightSinglePVEResMsg_6102_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FightSinglePVEResultReqMsg_6103_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FightSinglePVEResultReqMsg_6103_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FightSinglePVEResultResMsg_6104_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FightSinglePVEResultResMsg_6104_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016FightMsg.proto\032\016AwardMsg.proto\"\'\n\031Figh" +
      "tSinglePVEReqMsg_6101\022\n\n\002id\030\001 \001(\005\"7\n\031Fig" +
      "htSinglePVEResMsg_6102\022\016\n\006reulst\030\001 \001(\005\022\n" +
      "\n\002id\030\002 \001(\005\"M\n\037FightSinglePVEResultReqMsg" +
      "_6103\022\016\n\006report\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\016\n\006res" +
      "ult\030\003 \001(\005\"S\n\037FightSinglePVEResultResMsg_" +
      "6104\022\016\n\006result\030\001 \001(\005\022 \n\010dropList\030\002 \003(\0132\016" +
      ".AwardItemDataB\025\n\021xn.protobuf.fightH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FightSinglePVEReqMsg_6101_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FightSinglePVEReqMsg_6101_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FightSinglePVEReqMsg_6101_descriptor,
              new java.lang.String[] { "Id", });
          internal_static_FightSinglePVEResMsg_6102_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_FightSinglePVEResMsg_6102_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FightSinglePVEResMsg_6102_descriptor,
              new java.lang.String[] { "Reulst", "Id", });
          internal_static_FightSinglePVEResultReqMsg_6103_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_FightSinglePVEResultReqMsg_6103_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FightSinglePVEResultReqMsg_6103_descriptor,
              new java.lang.String[] { "Report", "Id", "Result", });
          internal_static_FightSinglePVEResultResMsg_6104_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_FightSinglePVEResultResMsg_6104_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FightSinglePVEResultResMsg_6104_descriptor,
              new java.lang.String[] { "Result", "DropList", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          xn.protobuf.award.AwardMsg.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
