// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NpcMsg.proto

package xn.protobuf.npc;

public final class NpcMsg {
  private NpcMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NpcTalkReqMsg_14001OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 npcId = 1;
    /**
     * <code>optional int32 npcId = 1;</code>
     */
    boolean hasNpcId();
    /**
     * <code>optional int32 npcId = 1;</code>
     */
    int getNpcId();

    // optional int32 taskId = 2;
    /**
     * <code>optional int32 taskId = 2;</code>
     *
     * <pre>
     *任务id
     * </pre>
     */
    boolean hasTaskId();
    /**
     * <code>optional int32 taskId = 2;</code>
     *
     * <pre>
     *任务id
     * </pre>
     */
    int getTaskId();
  }
  /**
   * Protobuf type {@code NpcTalkReqMsg_14001}
   *
   * <pre>
   *请求和NPC对话
   * </pre>
   */
  public static final class NpcTalkReqMsg_14001 extends
      com.google.protobuf.GeneratedMessage
      implements NpcTalkReqMsg_14001OrBuilder {
    // Use NpcTalkReqMsg_14001.newBuilder() to construct.
    private NpcTalkReqMsg_14001(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NpcTalkReqMsg_14001(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NpcTalkReqMsg_14001 defaultInstance;
    public static NpcTalkReqMsg_14001 getDefaultInstance() {
      return defaultInstance;
    }

    public NpcTalkReqMsg_14001 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NpcTalkReqMsg_14001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              npcId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              taskId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.npc.NpcMsg.internal_static_NpcTalkReqMsg_14001_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.npc.NpcMsg.internal_static_NpcTalkReqMsg_14001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001.class, xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001.Builder.class);
    }

    public static com.google.protobuf.Parser<NpcTalkReqMsg_14001> PARSER =
        new com.google.protobuf.AbstractParser<NpcTalkReqMsg_14001>() {
      public NpcTalkReqMsg_14001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NpcTalkReqMsg_14001(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NpcTalkReqMsg_14001> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 npcId = 1;
    public static final int NPCID_FIELD_NUMBER = 1;
    private int npcId_;
    /**
     * <code>optional int32 npcId = 1;</code>
     */
    public boolean hasNpcId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 npcId = 1;</code>
     */
    public int getNpcId() {
      return npcId_;
    }

    // optional int32 taskId = 2;
    public static final int TASKID_FIELD_NUMBER = 2;
    private int taskId_;
    /**
     * <code>optional int32 taskId = 2;</code>
     *
     * <pre>
     *任务id
     * </pre>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 taskId = 2;</code>
     *
     * <pre>
     *任务id
     * </pre>
     */
    public int getTaskId() {
      return taskId_;
    }

    private void initFields() {
      npcId_ = 0;
      taskId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, npcId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, taskId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, npcId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, taskId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NpcTalkReqMsg_14001}
     *
     * <pre>
     *请求和NPC对话
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.npc.NpcMsg.internal_static_NpcTalkReqMsg_14001_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.npc.NpcMsg.internal_static_NpcTalkReqMsg_14001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001.class, xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001.Builder.class);
      }

      // Construct using xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        npcId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.npc.NpcMsg.internal_static_NpcTalkReqMsg_14001_descriptor;
      }

      public xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 getDefaultInstanceForType() {
        return xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001.getDefaultInstance();
      }

      public xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 build() {
        xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 buildPartial() {
        xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 result = new xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.npcId_ = npcId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.taskId_ = taskId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001) {
          return mergeFrom((xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 other) {
        if (other == xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001.getDefaultInstance()) return this;
        if (other.hasNpcId()) {
          setNpcId(other.getNpcId());
        }
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.npc.NpcMsg.NpcTalkReqMsg_14001) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 npcId = 1;
      private int npcId_ ;
      /**
       * <code>optional int32 npcId = 1;</code>
       */
      public boolean hasNpcId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 npcId = 1;</code>
       */
      public int getNpcId() {
        return npcId_;
      }
      /**
       * <code>optional int32 npcId = 1;</code>
       */
      public Builder setNpcId(int value) {
        bitField0_ |= 0x00000001;
        npcId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 npcId = 1;</code>
       */
      public Builder clearNpcId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        npcId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 taskId = 2;
      private int taskId_ ;
      /**
       * <code>optional int32 taskId = 2;</code>
       *
       * <pre>
       *任务id
       * </pre>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 taskId = 2;</code>
       *
       * <pre>
       *任务id
       * </pre>
       */
      public int getTaskId() {
        return taskId_;
      }
      /**
       * <code>optional int32 taskId = 2;</code>
       *
       * <pre>
       *任务id
       * </pre>
       */
      public Builder setTaskId(int value) {
        bitField0_ |= 0x00000002;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 taskId = 2;</code>
       *
       * <pre>
       *任务id
       * </pre>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        taskId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NpcTalkReqMsg_14001)
    }

    static {
      defaultInstance = new NpcTalkReqMsg_14001(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NpcTalkReqMsg_14001)
  }

  public interface NpcTaklResMsg_14002OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 result = 1;
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *0不更新 1更新
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *0不更新 1更新
     * </pre>
     */
    int getResult();

    // optional .UpdateTaskData updateTaskData = 2;
    /**
     * <code>optional .UpdateTaskData updateTaskData = 2;</code>
     *
     * <pre>
     *更新任务数据
     * </pre>
     */
    boolean hasUpdateTaskData();
    /**
     * <code>optional .UpdateTaskData updateTaskData = 2;</code>
     *
     * <pre>
     *更新任务数据
     * </pre>
     */
    xn.protobuf.task.TaskMsg.UpdateTaskData getUpdateTaskData();
    /**
     * <code>optional .UpdateTaskData updateTaskData = 2;</code>
     *
     * <pre>
     *更新任务数据
     * </pre>
     */
    xn.protobuf.task.TaskMsg.UpdateTaskDataOrBuilder getUpdateTaskDataOrBuilder();
  }
  /**
   * Protobuf type {@code NpcTaklResMsg_14002}
   *
   * <pre>
   *返回结果
   * </pre>
   */
  public static final class NpcTaklResMsg_14002 extends
      com.google.protobuf.GeneratedMessage
      implements NpcTaklResMsg_14002OrBuilder {
    // Use NpcTaklResMsg_14002.newBuilder() to construct.
    private NpcTaklResMsg_14002(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NpcTaklResMsg_14002(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NpcTaklResMsg_14002 defaultInstance;
    public static NpcTaklResMsg_14002 getDefaultInstance() {
      return defaultInstance;
    }

    public NpcTaklResMsg_14002 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NpcTaklResMsg_14002(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              xn.protobuf.task.TaskMsg.UpdateTaskData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = updateTaskData_.toBuilder();
              }
              updateTaskData_ = input.readMessage(xn.protobuf.task.TaskMsg.UpdateTaskData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(updateTaskData_);
                updateTaskData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.npc.NpcMsg.internal_static_NpcTaklResMsg_14002_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.npc.NpcMsg.internal_static_NpcTaklResMsg_14002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002.class, xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002.Builder.class);
    }

    public static com.google.protobuf.Parser<NpcTaklResMsg_14002> PARSER =
        new com.google.protobuf.AbstractParser<NpcTaklResMsg_14002>() {
      public NpcTaklResMsg_14002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NpcTaklResMsg_14002(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NpcTaklResMsg_14002> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *0不更新 1更新
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *0不更新 1更新
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    // optional .UpdateTaskData updateTaskData = 2;
    public static final int UPDATETASKDATA_FIELD_NUMBER = 2;
    private xn.protobuf.task.TaskMsg.UpdateTaskData updateTaskData_;
    /**
     * <code>optional .UpdateTaskData updateTaskData = 2;</code>
     *
     * <pre>
     *更新任务数据
     * </pre>
     */
    public boolean hasUpdateTaskData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .UpdateTaskData updateTaskData = 2;</code>
     *
     * <pre>
     *更新任务数据
     * </pre>
     */
    public xn.protobuf.task.TaskMsg.UpdateTaskData getUpdateTaskData() {
      return updateTaskData_;
    }
    /**
     * <code>optional .UpdateTaskData updateTaskData = 2;</code>
     *
     * <pre>
     *更新任务数据
     * </pre>
     */
    public xn.protobuf.task.TaskMsg.UpdateTaskDataOrBuilder getUpdateTaskDataOrBuilder() {
      return updateTaskData_;
    }

    private void initFields() {
      result_ = 0;
      updateTaskData_ = xn.protobuf.task.TaskMsg.UpdateTaskData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, updateTaskData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, updateTaskData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NpcTaklResMsg_14002}
     *
     * <pre>
     *返回结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.npc.NpcMsg.internal_static_NpcTaklResMsg_14002_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.npc.NpcMsg.internal_static_NpcTaklResMsg_14002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002.class, xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002.Builder.class);
      }

      // Construct using xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUpdateTaskDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (updateTaskDataBuilder_ == null) {
          updateTaskData_ = xn.protobuf.task.TaskMsg.UpdateTaskData.getDefaultInstance();
        } else {
          updateTaskDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.npc.NpcMsg.internal_static_NpcTaklResMsg_14002_descriptor;
      }

      public xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 getDefaultInstanceForType() {
        return xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002.getDefaultInstance();
      }

      public xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 build() {
        xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 buildPartial() {
        xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 result = new xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (updateTaskDataBuilder_ == null) {
          result.updateTaskData_ = updateTaskData_;
        } else {
          result.updateTaskData_ = updateTaskDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002) {
          return mergeFrom((xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 other) {
        if (other == xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasUpdateTaskData()) {
          mergeUpdateTaskData(other.getUpdateTaskData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.npc.NpcMsg.NpcTaklResMsg_14002) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 result = 1;
      private int result_ ;
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *0不更新 1更新
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *0不更新 1更新
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *0不更新 1更新
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *0不更新 1更新
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // optional .UpdateTaskData updateTaskData = 2;
      private xn.protobuf.task.TaskMsg.UpdateTaskData updateTaskData_ = xn.protobuf.task.TaskMsg.UpdateTaskData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          xn.protobuf.task.TaskMsg.UpdateTaskData, xn.protobuf.task.TaskMsg.UpdateTaskData.Builder, xn.protobuf.task.TaskMsg.UpdateTaskDataOrBuilder> updateTaskDataBuilder_;
      /**
       * <code>optional .UpdateTaskData updateTaskData = 2;</code>
       *
       * <pre>
       *更新任务数据
       * </pre>
       */
      public boolean hasUpdateTaskData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .UpdateTaskData updateTaskData = 2;</code>
       *
       * <pre>
       *更新任务数据
       * </pre>
       */
      public xn.protobuf.task.TaskMsg.UpdateTaskData getUpdateTaskData() {
        if (updateTaskDataBuilder_ == null) {
          return updateTaskData_;
        } else {
          return updateTaskDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .UpdateTaskData updateTaskData = 2;</code>
       *
       * <pre>
       *更新任务数据
       * </pre>
       */
      public Builder setUpdateTaskData(xn.protobuf.task.TaskMsg.UpdateTaskData value) {
        if (updateTaskDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updateTaskData_ = value;
          onChanged();
        } else {
          updateTaskDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .UpdateTaskData updateTaskData = 2;</code>
       *
       * <pre>
       *更新任务数据
       * </pre>
       */
      public Builder setUpdateTaskData(
          xn.protobuf.task.TaskMsg.UpdateTaskData.Builder builderForValue) {
        if (updateTaskDataBuilder_ == null) {
          updateTaskData_ = builderForValue.build();
          onChanged();
        } else {
          updateTaskDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .UpdateTaskData updateTaskData = 2;</code>
       *
       * <pre>
       *更新任务数据
       * </pre>
       */
      public Builder mergeUpdateTaskData(xn.protobuf.task.TaskMsg.UpdateTaskData value) {
        if (updateTaskDataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              updateTaskData_ != xn.protobuf.task.TaskMsg.UpdateTaskData.getDefaultInstance()) {
            updateTaskData_ =
              xn.protobuf.task.TaskMsg.UpdateTaskData.newBuilder(updateTaskData_).mergeFrom(value).buildPartial();
          } else {
            updateTaskData_ = value;
          }
          onChanged();
        } else {
          updateTaskDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .UpdateTaskData updateTaskData = 2;</code>
       *
       * <pre>
       *更新任务数据
       * </pre>
       */
      public Builder clearUpdateTaskData() {
        if (updateTaskDataBuilder_ == null) {
          updateTaskData_ = xn.protobuf.task.TaskMsg.UpdateTaskData.getDefaultInstance();
          onChanged();
        } else {
          updateTaskDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .UpdateTaskData updateTaskData = 2;</code>
       *
       * <pre>
       *更新任务数据
       * </pre>
       */
      public xn.protobuf.task.TaskMsg.UpdateTaskData.Builder getUpdateTaskDataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUpdateTaskDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UpdateTaskData updateTaskData = 2;</code>
       *
       * <pre>
       *更新任务数据
       * </pre>
       */
      public xn.protobuf.task.TaskMsg.UpdateTaskDataOrBuilder getUpdateTaskDataOrBuilder() {
        if (updateTaskDataBuilder_ != null) {
          return updateTaskDataBuilder_.getMessageOrBuilder();
        } else {
          return updateTaskData_;
        }
      }
      /**
       * <code>optional .UpdateTaskData updateTaskData = 2;</code>
       *
       * <pre>
       *更新任务数据
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          xn.protobuf.task.TaskMsg.UpdateTaskData, xn.protobuf.task.TaskMsg.UpdateTaskData.Builder, xn.protobuf.task.TaskMsg.UpdateTaskDataOrBuilder> 
          getUpdateTaskDataFieldBuilder() {
        if (updateTaskDataBuilder_ == null) {
          updateTaskDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              xn.protobuf.task.TaskMsg.UpdateTaskData, xn.protobuf.task.TaskMsg.UpdateTaskData.Builder, xn.protobuf.task.TaskMsg.UpdateTaskDataOrBuilder>(
                  updateTaskData_,
                  getParentForChildren(),
                  isClean());
          updateTaskData_ = null;
        }
        return updateTaskDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:NpcTaklResMsg_14002)
    }

    static {
      defaultInstance = new NpcTaklResMsg_14002(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NpcTaklResMsg_14002)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NpcTalkReqMsg_14001_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NpcTalkReqMsg_14001_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NpcTaklResMsg_14002_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NpcTaklResMsg_14002_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014NpcMsg.proto\032\rTaskMsg.proto\"4\n\023NpcTalk" +
      "ReqMsg_14001\022\r\n\005npcId\030\001 \001(\005\022\016\n\006taskId\030\002 " +
      "\001(\005\"N\n\023NpcTaklResMsg_14002\022\016\n\006result\030\001 \001" +
      "(\005\022\'\n\016updateTaskData\030\002 \001(\0132\017.UpdateTaskD" +
      "ataB\023\n\017xn.protobuf.npcH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NpcTalkReqMsg_14001_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NpcTalkReqMsg_14001_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NpcTalkReqMsg_14001_descriptor,
              new java.lang.String[] { "NpcId", "TaskId", });
          internal_static_NpcTaklResMsg_14002_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_NpcTaklResMsg_14002_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NpcTaklResMsg_14002_descriptor,
              new java.lang.String[] { "Result", "UpdateTaskData", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          xn.protobuf.task.TaskMsg.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
