// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RuneMsg.proto

package xn.protobuf.rune;

public final class RuneMsg {
  private RuneMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RuneComposeReqMsg_18001OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 itemId = 1;
    /**
     * <code>optional int32 itemId = 1;</code>
     *
     * <pre>
     *符文道具id
     * </pre>
     */
    boolean hasItemId();
    /**
     * <code>optional int32 itemId = 1;</code>
     *
     * <pre>
     *符文道具id
     * </pre>
     */
    int getItemId();

    // optional int32 count = 2;
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     *合成目标符文的数量
     * </pre>
     */
    boolean hasCount();
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     *合成目标符文的数量
     * </pre>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code RuneComposeReqMsg_18001}
   *
   * <pre>
   *请求合成符文
   * </pre>
   */
  public static final class RuneComposeReqMsg_18001 extends
      com.google.protobuf.GeneratedMessage
      implements RuneComposeReqMsg_18001OrBuilder {
    // Use RuneComposeReqMsg_18001.newBuilder() to construct.
    private RuneComposeReqMsg_18001(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RuneComposeReqMsg_18001(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RuneComposeReqMsg_18001 defaultInstance;
    public static RuneComposeReqMsg_18001 getDefaultInstance() {
      return defaultInstance;
    }

    public RuneComposeReqMsg_18001 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RuneComposeReqMsg_18001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              itemId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.rune.RuneMsg.internal_static_RuneComposeReqMsg_18001_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.rune.RuneMsg.internal_static_RuneComposeReqMsg_18001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001.class, xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001.Builder.class);
    }

    public static com.google.protobuf.Parser<RuneComposeReqMsg_18001> PARSER =
        new com.google.protobuf.AbstractParser<RuneComposeReqMsg_18001>() {
      public RuneComposeReqMsg_18001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RuneComposeReqMsg_18001(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RuneComposeReqMsg_18001> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 itemId = 1;
    public static final int ITEMID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <code>optional int32 itemId = 1;</code>
     *
     * <pre>
     *符文道具id
     * </pre>
     */
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 itemId = 1;</code>
     *
     * <pre>
     *符文道具id
     * </pre>
     */
    public int getItemId() {
      return itemId_;
    }

    // optional int32 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     *合成目标符文的数量
     * </pre>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     *合成目标符文的数量
     * </pre>
     */
    public int getCount() {
      return count_;
    }

    private void initFields() {
      itemId_ = 0;
      count_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, itemId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RuneComposeReqMsg_18001}
     *
     * <pre>
     *请求合成符文
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneComposeReqMsg_18001_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneComposeReqMsg_18001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001.class, xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001.Builder.class);
      }

      // Construct using xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        itemId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneComposeReqMsg_18001_descriptor;
      }

      public xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 getDefaultInstanceForType() {
        return xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001.getDefaultInstance();
      }

      public xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 build() {
        xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 buildPartial() {
        xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 result = new xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.itemId_ = itemId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001) {
          return mergeFrom((xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 other) {
        if (other == xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001.getDefaultInstance()) return this;
        if (other.hasItemId()) {
          setItemId(other.getItemId());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.rune.RuneMsg.RuneComposeReqMsg_18001) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 itemId = 1;
      private int itemId_ ;
      /**
       * <code>optional int32 itemId = 1;</code>
       *
       * <pre>
       *符文道具id
       * </pre>
       */
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 itemId = 1;</code>
       *
       * <pre>
       *符文道具id
       * </pre>
       */
      public int getItemId() {
        return itemId_;
      }
      /**
       * <code>optional int32 itemId = 1;</code>
       *
       * <pre>
       *符文道具id
       * </pre>
       */
      public Builder setItemId(int value) {
        bitField0_ |= 0x00000001;
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 itemId = 1;</code>
       *
       * <pre>
       *符文道具id
       * </pre>
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 count = 2;
      private int count_ ;
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       *合成目标符文的数量
       * </pre>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       *合成目标符文的数量
       * </pre>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       *合成目标符文的数量
       * </pre>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       *合成目标符文的数量
       * </pre>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RuneComposeReqMsg_18001)
    }

    static {
      defaultInstance = new RuneComposeReqMsg_18001(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RuneComposeReqMsg_18001)
  }

  public interface RuneComposeResMsg_18002OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .PlayerBaseData playerBaseData = 1;
    /**
     * <code>optional .PlayerBaseData playerBaseData = 1;</code>
     */
    boolean hasPlayerBaseData();
    /**
     * <code>optional .PlayerBaseData playerBaseData = 1;</code>
     */
    xn.protobuf.player.PlayerMsg.PlayerBaseData getPlayerBaseData();
    /**
     * <code>optional .PlayerBaseData playerBaseData = 1;</code>
     */
    xn.protobuf.player.PlayerMsg.PlayerBaseDataOrBuilder getPlayerBaseDataOrBuilder();
  }
  /**
   * Protobuf type {@code RuneComposeResMsg_18002}
   *
   * <pre>
   *返回合成符文结果
   * </pre>
   */
  public static final class RuneComposeResMsg_18002 extends
      com.google.protobuf.GeneratedMessage
      implements RuneComposeResMsg_18002OrBuilder {
    // Use RuneComposeResMsg_18002.newBuilder() to construct.
    private RuneComposeResMsg_18002(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RuneComposeResMsg_18002(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RuneComposeResMsg_18002 defaultInstance;
    public static RuneComposeResMsg_18002 getDefaultInstance() {
      return defaultInstance;
    }

    public RuneComposeResMsg_18002 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RuneComposeResMsg_18002(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              xn.protobuf.player.PlayerMsg.PlayerBaseData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = playerBaseData_.toBuilder();
              }
              playerBaseData_ = input.readMessage(xn.protobuf.player.PlayerMsg.PlayerBaseData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(playerBaseData_);
                playerBaseData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.rune.RuneMsg.internal_static_RuneComposeResMsg_18002_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.rune.RuneMsg.internal_static_RuneComposeResMsg_18002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002.class, xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002.Builder.class);
    }

    public static com.google.protobuf.Parser<RuneComposeResMsg_18002> PARSER =
        new com.google.protobuf.AbstractParser<RuneComposeResMsg_18002>() {
      public RuneComposeResMsg_18002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RuneComposeResMsg_18002(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RuneComposeResMsg_18002> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .PlayerBaseData playerBaseData = 1;
    public static final int PLAYERBASEDATA_FIELD_NUMBER = 1;
    private xn.protobuf.player.PlayerMsg.PlayerBaseData playerBaseData_;
    /**
     * <code>optional .PlayerBaseData playerBaseData = 1;</code>
     */
    public boolean hasPlayerBaseData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .PlayerBaseData playerBaseData = 1;</code>
     */
    public xn.protobuf.player.PlayerMsg.PlayerBaseData getPlayerBaseData() {
      return playerBaseData_;
    }
    /**
     * <code>optional .PlayerBaseData playerBaseData = 1;</code>
     */
    public xn.protobuf.player.PlayerMsg.PlayerBaseDataOrBuilder getPlayerBaseDataOrBuilder() {
      return playerBaseData_;
    }

    private void initFields() {
      playerBaseData_ = xn.protobuf.player.PlayerMsg.PlayerBaseData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, playerBaseData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, playerBaseData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RuneComposeResMsg_18002}
     *
     * <pre>
     *返回合成符文结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneComposeResMsg_18002_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneComposeResMsg_18002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002.class, xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002.Builder.class);
      }

      // Construct using xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayerBaseDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (playerBaseDataBuilder_ == null) {
          playerBaseData_ = xn.protobuf.player.PlayerMsg.PlayerBaseData.getDefaultInstance();
        } else {
          playerBaseDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneComposeResMsg_18002_descriptor;
      }

      public xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 getDefaultInstanceForType() {
        return xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002.getDefaultInstance();
      }

      public xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 build() {
        xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 buildPartial() {
        xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 result = new xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (playerBaseDataBuilder_ == null) {
          result.playerBaseData_ = playerBaseData_;
        } else {
          result.playerBaseData_ = playerBaseDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002) {
          return mergeFrom((xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 other) {
        if (other == xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002.getDefaultInstance()) return this;
        if (other.hasPlayerBaseData()) {
          mergePlayerBaseData(other.getPlayerBaseData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.rune.RuneMsg.RuneComposeResMsg_18002) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .PlayerBaseData playerBaseData = 1;
      private xn.protobuf.player.PlayerMsg.PlayerBaseData playerBaseData_ = xn.protobuf.player.PlayerMsg.PlayerBaseData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          xn.protobuf.player.PlayerMsg.PlayerBaseData, xn.protobuf.player.PlayerMsg.PlayerBaseData.Builder, xn.protobuf.player.PlayerMsg.PlayerBaseDataOrBuilder> playerBaseDataBuilder_;
      /**
       * <code>optional .PlayerBaseData playerBaseData = 1;</code>
       */
      public boolean hasPlayerBaseData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .PlayerBaseData playerBaseData = 1;</code>
       */
      public xn.protobuf.player.PlayerMsg.PlayerBaseData getPlayerBaseData() {
        if (playerBaseDataBuilder_ == null) {
          return playerBaseData_;
        } else {
          return playerBaseDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PlayerBaseData playerBaseData = 1;</code>
       */
      public Builder setPlayerBaseData(xn.protobuf.player.PlayerMsg.PlayerBaseData value) {
        if (playerBaseDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerBaseData_ = value;
          onChanged();
        } else {
          playerBaseDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PlayerBaseData playerBaseData = 1;</code>
       */
      public Builder setPlayerBaseData(
          xn.protobuf.player.PlayerMsg.PlayerBaseData.Builder builderForValue) {
        if (playerBaseDataBuilder_ == null) {
          playerBaseData_ = builderForValue.build();
          onChanged();
        } else {
          playerBaseDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PlayerBaseData playerBaseData = 1;</code>
       */
      public Builder mergePlayerBaseData(xn.protobuf.player.PlayerMsg.PlayerBaseData value) {
        if (playerBaseDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              playerBaseData_ != xn.protobuf.player.PlayerMsg.PlayerBaseData.getDefaultInstance()) {
            playerBaseData_ =
              xn.protobuf.player.PlayerMsg.PlayerBaseData.newBuilder(playerBaseData_).mergeFrom(value).buildPartial();
          } else {
            playerBaseData_ = value;
          }
          onChanged();
        } else {
          playerBaseDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PlayerBaseData playerBaseData = 1;</code>
       */
      public Builder clearPlayerBaseData() {
        if (playerBaseDataBuilder_ == null) {
          playerBaseData_ = xn.protobuf.player.PlayerMsg.PlayerBaseData.getDefaultInstance();
          onChanged();
        } else {
          playerBaseDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .PlayerBaseData playerBaseData = 1;</code>
       */
      public xn.protobuf.player.PlayerMsg.PlayerBaseData.Builder getPlayerBaseDataBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPlayerBaseDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PlayerBaseData playerBaseData = 1;</code>
       */
      public xn.protobuf.player.PlayerMsg.PlayerBaseDataOrBuilder getPlayerBaseDataOrBuilder() {
        if (playerBaseDataBuilder_ != null) {
          return playerBaseDataBuilder_.getMessageOrBuilder();
        } else {
          return playerBaseData_;
        }
      }
      /**
       * <code>optional .PlayerBaseData playerBaseData = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          xn.protobuf.player.PlayerMsg.PlayerBaseData, xn.protobuf.player.PlayerMsg.PlayerBaseData.Builder, xn.protobuf.player.PlayerMsg.PlayerBaseDataOrBuilder> 
          getPlayerBaseDataFieldBuilder() {
        if (playerBaseDataBuilder_ == null) {
          playerBaseDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              xn.protobuf.player.PlayerMsg.PlayerBaseData, xn.protobuf.player.PlayerMsg.PlayerBaseData.Builder, xn.protobuf.player.PlayerMsg.PlayerBaseDataOrBuilder>(
                  playerBaseData_,
                  getParentForChildren(),
                  isClean());
          playerBaseData_ = null;
        }
        return playerBaseDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:RuneComposeResMsg_18002)
    }

    static {
      defaultInstance = new RuneComposeResMsg_18002(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RuneComposeResMsg_18002)
  }

  public interface RuneSetReqMsg_18003OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string runes = 1;
    /**
     * <code>optional string runes = 1;</code>
     *
     * <pre>
     *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    boolean hasRunes();
    /**
     * <code>optional string runes = 1;</code>
     *
     * <pre>
     *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    java.lang.String getRunes();
    /**
     * <code>optional string runes = 1;</code>
     *
     * <pre>
     *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    com.google.protobuf.ByteString
        getRunesBytes();
  }
  /**
   * Protobuf type {@code RuneSetReqMsg_18003}
   *
   * <pre>
   *请求设置符文
   * </pre>
   */
  public static final class RuneSetReqMsg_18003 extends
      com.google.protobuf.GeneratedMessage
      implements RuneSetReqMsg_18003OrBuilder {
    // Use RuneSetReqMsg_18003.newBuilder() to construct.
    private RuneSetReqMsg_18003(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RuneSetReqMsg_18003(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RuneSetReqMsg_18003 defaultInstance;
    public static RuneSetReqMsg_18003 getDefaultInstance() {
      return defaultInstance;
    }

    public RuneSetReqMsg_18003 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RuneSetReqMsg_18003(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              runes_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.rune.RuneMsg.internal_static_RuneSetReqMsg_18003_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.rune.RuneMsg.internal_static_RuneSetReqMsg_18003_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003.class, xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003.Builder.class);
    }

    public static com.google.protobuf.Parser<RuneSetReqMsg_18003> PARSER =
        new com.google.protobuf.AbstractParser<RuneSetReqMsg_18003>() {
      public RuneSetReqMsg_18003 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RuneSetReqMsg_18003(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RuneSetReqMsg_18003> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string runes = 1;
    public static final int RUNES_FIELD_NUMBER = 1;
    private java.lang.Object runes_;
    /**
     * <code>optional string runes = 1;</code>
     *
     * <pre>
     *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    public boolean hasRunes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string runes = 1;</code>
     *
     * <pre>
     *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    public java.lang.String getRunes() {
      java.lang.Object ref = runes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          runes_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string runes = 1;</code>
     *
     * <pre>
     *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRunesBytes() {
      java.lang.Object ref = runes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      runes_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRunesBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRunesBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RuneSetReqMsg_18003}
     *
     * <pre>
     *请求设置符文
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneSetReqMsg_18003_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneSetReqMsg_18003_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003.class, xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003.Builder.class);
      }

      // Construct using xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        runes_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneSetReqMsg_18003_descriptor;
      }

      public xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 getDefaultInstanceForType() {
        return xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003.getDefaultInstance();
      }

      public xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 build() {
        xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 buildPartial() {
        xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 result = new xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.runes_ = runes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003) {
          return mergeFrom((xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 other) {
        if (other == xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003.getDefaultInstance()) return this;
        if (other.hasRunes()) {
          bitField0_ |= 0x00000001;
          runes_ = other.runes_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.rune.RuneMsg.RuneSetReqMsg_18003) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string runes = 1;
      private java.lang.Object runes_ = "";
      /**
       * <code>optional string runes = 1;</code>
       *
       * <pre>
       *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public boolean hasRunes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string runes = 1;</code>
       *
       * <pre>
       *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public java.lang.String getRunes() {
        java.lang.Object ref = runes_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          runes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string runes = 1;</code>
       *
       * <pre>
       *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRunesBytes() {
        java.lang.Object ref = runes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          runes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string runes = 1;</code>
       *
       * <pre>
       *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public Builder setRunes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        runes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string runes = 1;</code>
       *
       * <pre>
       *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public Builder clearRunes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        runes_ = getDefaultInstance().getRunes();
        onChanged();
        return this;
      }
      /**
       * <code>optional string runes = 1;</code>
       *
       * <pre>
       *例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public Builder setRunesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        runes_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RuneSetReqMsg_18003)
    }

    static {
      defaultInstance = new RuneSetReqMsg_18003(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RuneSetReqMsg_18003)
  }

  public interface RuneSetResMsg_18004OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .PlayerFightData playerFightData = 1;
    /**
     * <code>optional .PlayerFightData playerFightData = 1;</code>
     *
     * <pre>
     *玩家战斗相关数值
     * </pre>
     */
    boolean hasPlayerFightData();
    /**
     * <code>optional .PlayerFightData playerFightData = 1;</code>
     *
     * <pre>
     *玩家战斗相关数值
     * </pre>
     */
    xn.protobuf.player.PlayerMsg.PlayerFightData getPlayerFightData();
    /**
     * <code>optional .PlayerFightData playerFightData = 1;</code>
     *
     * <pre>
     *玩家战斗相关数值
     * </pre>
     */
    xn.protobuf.player.PlayerMsg.PlayerFightDataOrBuilder getPlayerFightDataOrBuilder();

    // optional string runeList = 2;
    /**
     * <code>optional string runeList = 2;</code>
     *
     * <pre>
     *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    boolean hasRuneList();
    /**
     * <code>optional string runeList = 2;</code>
     *
     * <pre>
     *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    java.lang.String getRuneList();
    /**
     * <code>optional string runeList = 2;</code>
     *
     * <pre>
     *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    com.google.protobuf.ByteString
        getRuneListBytes();
  }
  /**
   * Protobuf type {@code RuneSetResMsg_18004}
   *
   * <pre>
   *返回设置符文结果
   * </pre>
   */
  public static final class RuneSetResMsg_18004 extends
      com.google.protobuf.GeneratedMessage
      implements RuneSetResMsg_18004OrBuilder {
    // Use RuneSetResMsg_18004.newBuilder() to construct.
    private RuneSetResMsg_18004(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RuneSetResMsg_18004(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RuneSetResMsg_18004 defaultInstance;
    public static RuneSetResMsg_18004 getDefaultInstance() {
      return defaultInstance;
    }

    public RuneSetResMsg_18004 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RuneSetResMsg_18004(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              xn.protobuf.player.PlayerMsg.PlayerFightData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = playerFightData_.toBuilder();
              }
              playerFightData_ = input.readMessage(xn.protobuf.player.PlayerMsg.PlayerFightData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(playerFightData_);
                playerFightData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              runeList_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.rune.RuneMsg.internal_static_RuneSetResMsg_18004_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.rune.RuneMsg.internal_static_RuneSetResMsg_18004_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004.class, xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004.Builder.class);
    }

    public static com.google.protobuf.Parser<RuneSetResMsg_18004> PARSER =
        new com.google.protobuf.AbstractParser<RuneSetResMsg_18004>() {
      public RuneSetResMsg_18004 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RuneSetResMsg_18004(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RuneSetResMsg_18004> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .PlayerFightData playerFightData = 1;
    public static final int PLAYERFIGHTDATA_FIELD_NUMBER = 1;
    private xn.protobuf.player.PlayerMsg.PlayerFightData playerFightData_;
    /**
     * <code>optional .PlayerFightData playerFightData = 1;</code>
     *
     * <pre>
     *玩家战斗相关数值
     * </pre>
     */
    public boolean hasPlayerFightData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .PlayerFightData playerFightData = 1;</code>
     *
     * <pre>
     *玩家战斗相关数值
     * </pre>
     */
    public xn.protobuf.player.PlayerMsg.PlayerFightData getPlayerFightData() {
      return playerFightData_;
    }
    /**
     * <code>optional .PlayerFightData playerFightData = 1;</code>
     *
     * <pre>
     *玩家战斗相关数值
     * </pre>
     */
    public xn.protobuf.player.PlayerMsg.PlayerFightDataOrBuilder getPlayerFightDataOrBuilder() {
      return playerFightData_;
    }

    // optional string runeList = 2;
    public static final int RUNELIST_FIELD_NUMBER = 2;
    private java.lang.Object runeList_;
    /**
     * <code>optional string runeList = 2;</code>
     *
     * <pre>
     *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    public boolean hasRuneList() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string runeList = 2;</code>
     *
     * <pre>
     *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    public java.lang.String getRuneList() {
      java.lang.Object ref = runeList_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          runeList_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string runeList = 2;</code>
     *
     * <pre>
     *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRuneListBytes() {
      java.lang.Object ref = runeList_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runeList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      playerFightData_ = xn.protobuf.player.PlayerMsg.PlayerFightData.getDefaultInstance();
      runeList_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, playerFightData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRuneListBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, playerFightData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRuneListBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RuneSetResMsg_18004}
     *
     * <pre>
     *返回设置符文结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneSetResMsg_18004_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneSetResMsg_18004_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004.class, xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004.Builder.class);
      }

      // Construct using xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayerFightDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (playerFightDataBuilder_ == null) {
          playerFightData_ = xn.protobuf.player.PlayerMsg.PlayerFightData.getDefaultInstance();
        } else {
          playerFightDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        runeList_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.rune.RuneMsg.internal_static_RuneSetResMsg_18004_descriptor;
      }

      public xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 getDefaultInstanceForType() {
        return xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004.getDefaultInstance();
      }

      public xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 build() {
        xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 buildPartial() {
        xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 result = new xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (playerFightDataBuilder_ == null) {
          result.playerFightData_ = playerFightData_;
        } else {
          result.playerFightData_ = playerFightDataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.runeList_ = runeList_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004) {
          return mergeFrom((xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 other) {
        if (other == xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004.getDefaultInstance()) return this;
        if (other.hasPlayerFightData()) {
          mergePlayerFightData(other.getPlayerFightData());
        }
        if (other.hasRuneList()) {
          bitField0_ |= 0x00000002;
          runeList_ = other.runeList_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.rune.RuneMsg.RuneSetResMsg_18004) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .PlayerFightData playerFightData = 1;
      private xn.protobuf.player.PlayerMsg.PlayerFightData playerFightData_ = xn.protobuf.player.PlayerMsg.PlayerFightData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          xn.protobuf.player.PlayerMsg.PlayerFightData, xn.protobuf.player.PlayerMsg.PlayerFightData.Builder, xn.protobuf.player.PlayerMsg.PlayerFightDataOrBuilder> playerFightDataBuilder_;
      /**
       * <code>optional .PlayerFightData playerFightData = 1;</code>
       *
       * <pre>
       *玩家战斗相关数值
       * </pre>
       */
      public boolean hasPlayerFightData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .PlayerFightData playerFightData = 1;</code>
       *
       * <pre>
       *玩家战斗相关数值
       * </pre>
       */
      public xn.protobuf.player.PlayerMsg.PlayerFightData getPlayerFightData() {
        if (playerFightDataBuilder_ == null) {
          return playerFightData_;
        } else {
          return playerFightDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PlayerFightData playerFightData = 1;</code>
       *
       * <pre>
       *玩家战斗相关数值
       * </pre>
       */
      public Builder setPlayerFightData(xn.protobuf.player.PlayerMsg.PlayerFightData value) {
        if (playerFightDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerFightData_ = value;
          onChanged();
        } else {
          playerFightDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PlayerFightData playerFightData = 1;</code>
       *
       * <pre>
       *玩家战斗相关数值
       * </pre>
       */
      public Builder setPlayerFightData(
          xn.protobuf.player.PlayerMsg.PlayerFightData.Builder builderForValue) {
        if (playerFightDataBuilder_ == null) {
          playerFightData_ = builderForValue.build();
          onChanged();
        } else {
          playerFightDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PlayerFightData playerFightData = 1;</code>
       *
       * <pre>
       *玩家战斗相关数值
       * </pre>
       */
      public Builder mergePlayerFightData(xn.protobuf.player.PlayerMsg.PlayerFightData value) {
        if (playerFightDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              playerFightData_ != xn.protobuf.player.PlayerMsg.PlayerFightData.getDefaultInstance()) {
            playerFightData_ =
              xn.protobuf.player.PlayerMsg.PlayerFightData.newBuilder(playerFightData_).mergeFrom(value).buildPartial();
          } else {
            playerFightData_ = value;
          }
          onChanged();
        } else {
          playerFightDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PlayerFightData playerFightData = 1;</code>
       *
       * <pre>
       *玩家战斗相关数值
       * </pre>
       */
      public Builder clearPlayerFightData() {
        if (playerFightDataBuilder_ == null) {
          playerFightData_ = xn.protobuf.player.PlayerMsg.PlayerFightData.getDefaultInstance();
          onChanged();
        } else {
          playerFightDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .PlayerFightData playerFightData = 1;</code>
       *
       * <pre>
       *玩家战斗相关数值
       * </pre>
       */
      public xn.protobuf.player.PlayerMsg.PlayerFightData.Builder getPlayerFightDataBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPlayerFightDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PlayerFightData playerFightData = 1;</code>
       *
       * <pre>
       *玩家战斗相关数值
       * </pre>
       */
      public xn.protobuf.player.PlayerMsg.PlayerFightDataOrBuilder getPlayerFightDataOrBuilder() {
        if (playerFightDataBuilder_ != null) {
          return playerFightDataBuilder_.getMessageOrBuilder();
        } else {
          return playerFightData_;
        }
      }
      /**
       * <code>optional .PlayerFightData playerFightData = 1;</code>
       *
       * <pre>
       *玩家战斗相关数值
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          xn.protobuf.player.PlayerMsg.PlayerFightData, xn.protobuf.player.PlayerMsg.PlayerFightData.Builder, xn.protobuf.player.PlayerMsg.PlayerFightDataOrBuilder> 
          getPlayerFightDataFieldBuilder() {
        if (playerFightDataBuilder_ == null) {
          playerFightDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              xn.protobuf.player.PlayerMsg.PlayerFightData, xn.protobuf.player.PlayerMsg.PlayerFightData.Builder, xn.protobuf.player.PlayerMsg.PlayerFightDataOrBuilder>(
                  playerFightData_,
                  getParentForChildren(),
                  isClean());
          playerFightData_ = null;
        }
        return playerFightDataBuilder_;
      }

      // optional string runeList = 2;
      private java.lang.Object runeList_ = "";
      /**
       * <code>optional string runeList = 2;</code>
       *
       * <pre>
       *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public boolean hasRuneList() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string runeList = 2;</code>
       *
       * <pre>
       *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public java.lang.String getRuneList() {
        java.lang.Object ref = runeList_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          runeList_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string runeList = 2;</code>
       *
       * <pre>
       *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRuneListBytes() {
        java.lang.Object ref = runeList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          runeList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string runeList = 2;</code>
       *
       * <pre>
       *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public Builder setRuneList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        runeList_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string runeList = 2;</code>
       *
       * <pre>
       *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public Builder clearRuneList() {
        bitField0_ = (bitField0_ & ~0x00000002);
        runeList_ = getDefaultInstance().getRuneList();
        onChanged();
        return this;
      }
      /**
       * <code>optional string runeList = 2;</code>
       *
       * <pre>
       *符文id列表 例如 4000001,4000002,0,-1,-1,-1,-1,-1,-1(0是未放置，-1不可放置)
       * </pre>
       */
      public Builder setRuneListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        runeList_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RuneSetResMsg_18004)
    }

    static {
      defaultInstance = new RuneSetResMsg_18004(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RuneSetResMsg_18004)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RuneComposeReqMsg_18001_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RuneComposeReqMsg_18001_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RuneComposeResMsg_18002_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RuneComposeResMsg_18002_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RuneSetReqMsg_18003_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RuneSetReqMsg_18003_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RuneSetResMsg_18004_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RuneSetResMsg_18004_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRuneMsg.proto\032\017PlayerMsg.proto\"8\n\027Rune" +
      "ComposeReqMsg_18001\022\016\n\006itemId\030\001 \001(\005\022\r\n\005c" +
      "ount\030\002 \001(\005\"B\n\027RuneComposeResMsg_18002\022\'\n" +
      "\016playerBaseData\030\001 \001(\0132\017.PlayerBaseData\"$" +
      "\n\023RuneSetReqMsg_18003\022\r\n\005runes\030\001 \001(\t\"R\n\023" +
      "RuneSetResMsg_18004\022)\n\017playerFightData\030\001" +
      " \001(\0132\020.PlayerFightData\022\020\n\010runeList\030\002 \001(\t" +
      "B\024\n\020xn.protobuf.runeH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RuneComposeReqMsg_18001_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RuneComposeReqMsg_18001_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RuneComposeReqMsg_18001_descriptor,
              new java.lang.String[] { "ItemId", "Count", });
          internal_static_RuneComposeResMsg_18002_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RuneComposeResMsg_18002_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RuneComposeResMsg_18002_descriptor,
              new java.lang.String[] { "PlayerBaseData", });
          internal_static_RuneSetReqMsg_18003_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_RuneSetReqMsg_18003_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RuneSetReqMsg_18003_descriptor,
              new java.lang.String[] { "Runes", });
          internal_static_RuneSetResMsg_18004_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_RuneSetResMsg_18004_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RuneSetResMsg_18004_descriptor,
              new java.lang.String[] { "PlayerFightData", "RuneList", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          xn.protobuf.player.PlayerMsg.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
