// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMsg.proto

package xn.protobuf.test;

public final class TestMsg {
  private TestMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestReqMsg_21001OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code TestReqMsg_21001}
   *
   * <pre>
   *请求获取可接任务列表
   * </pre>
   */
  public static final class TestReqMsg_21001 extends
      com.google.protobuf.GeneratedMessage
      implements TestReqMsg_21001OrBuilder {
    // Use TestReqMsg_21001.newBuilder() to construct.
    private TestReqMsg_21001(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestReqMsg_21001(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestReqMsg_21001 defaultInstance;
    public static TestReqMsg_21001 getDefaultInstance() {
      return defaultInstance;
    }

    public TestReqMsg_21001 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestReqMsg_21001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.test.TestMsg.internal_static_TestReqMsg_21001_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.test.TestMsg.internal_static_TestReqMsg_21001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.test.TestMsg.TestReqMsg_21001.class, xn.protobuf.test.TestMsg.TestReqMsg_21001.Builder.class);
    }

    public static com.google.protobuf.Parser<TestReqMsg_21001> PARSER =
        new com.google.protobuf.AbstractParser<TestReqMsg_21001>() {
      public TestReqMsg_21001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestReqMsg_21001(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestReqMsg_21001> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.test.TestMsg.TestReqMsg_21001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.test.TestMsg.TestReqMsg_21001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.test.TestMsg.TestReqMsg_21001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.test.TestMsg.TestReqMsg_21001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.test.TestMsg.TestReqMsg_21001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.test.TestMsg.TestReqMsg_21001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.test.TestMsg.TestReqMsg_21001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.test.TestMsg.TestReqMsg_21001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.test.TestMsg.TestReqMsg_21001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.test.TestMsg.TestReqMsg_21001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.test.TestMsg.TestReqMsg_21001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestReqMsg_21001}
     *
     * <pre>
     *请求获取可接任务列表
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.test.TestMsg.TestReqMsg_21001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.test.TestMsg.internal_static_TestReqMsg_21001_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.test.TestMsg.internal_static_TestReqMsg_21001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.test.TestMsg.TestReqMsg_21001.class, xn.protobuf.test.TestMsg.TestReqMsg_21001.Builder.class);
      }

      // Construct using xn.protobuf.test.TestMsg.TestReqMsg_21001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.test.TestMsg.internal_static_TestReqMsg_21001_descriptor;
      }

      public xn.protobuf.test.TestMsg.TestReqMsg_21001 getDefaultInstanceForType() {
        return xn.protobuf.test.TestMsg.TestReqMsg_21001.getDefaultInstance();
      }

      public xn.protobuf.test.TestMsg.TestReqMsg_21001 build() {
        xn.protobuf.test.TestMsg.TestReqMsg_21001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.test.TestMsg.TestReqMsg_21001 buildPartial() {
        xn.protobuf.test.TestMsg.TestReqMsg_21001 result = new xn.protobuf.test.TestMsg.TestReqMsg_21001(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.test.TestMsg.TestReqMsg_21001) {
          return mergeFrom((xn.protobuf.test.TestMsg.TestReqMsg_21001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.test.TestMsg.TestReqMsg_21001 other) {
        if (other == xn.protobuf.test.TestMsg.TestReqMsg_21001.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.test.TestMsg.TestReqMsg_21001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.test.TestMsg.TestReqMsg_21001) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TestReqMsg_21001)
    }

    static {
      defaultInstance = new TestReqMsg_21001(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TestReqMsg_21001)
  }

  public interface TestResMsg_21002OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code TestResMsg_21002}
   *
   * <pre>
   *返回可接任务列表
   * </pre>
   */
  public static final class TestResMsg_21002 extends
      com.google.protobuf.GeneratedMessage
      implements TestResMsg_21002OrBuilder {
    // Use TestResMsg_21002.newBuilder() to construct.
    private TestResMsg_21002(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestResMsg_21002(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestResMsg_21002 defaultInstance;
    public static TestResMsg_21002 getDefaultInstance() {
      return defaultInstance;
    }

    public TestResMsg_21002 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestResMsg_21002(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xn.protobuf.test.TestMsg.internal_static_TestResMsg_21002_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xn.protobuf.test.TestMsg.internal_static_TestResMsg_21002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xn.protobuf.test.TestMsg.TestResMsg_21002.class, xn.protobuf.test.TestMsg.TestResMsg_21002.Builder.class);
    }

    public static com.google.protobuf.Parser<TestResMsg_21002> PARSER =
        new com.google.protobuf.AbstractParser<TestResMsg_21002>() {
      public TestResMsg_21002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestResMsg_21002(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestResMsg_21002> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xn.protobuf.test.TestMsg.TestResMsg_21002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.test.TestMsg.TestResMsg_21002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.test.TestMsg.TestResMsg_21002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xn.protobuf.test.TestMsg.TestResMsg_21002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xn.protobuf.test.TestMsg.TestResMsg_21002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.test.TestMsg.TestResMsg_21002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xn.protobuf.test.TestMsg.TestResMsg_21002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xn.protobuf.test.TestMsg.TestResMsg_21002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xn.protobuf.test.TestMsg.TestResMsg_21002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xn.protobuf.test.TestMsg.TestResMsg_21002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xn.protobuf.test.TestMsg.TestResMsg_21002 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestResMsg_21002}
     *
     * <pre>
     *返回可接任务列表
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xn.protobuf.test.TestMsg.TestResMsg_21002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xn.protobuf.test.TestMsg.internal_static_TestResMsg_21002_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xn.protobuf.test.TestMsg.internal_static_TestResMsg_21002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xn.protobuf.test.TestMsg.TestResMsg_21002.class, xn.protobuf.test.TestMsg.TestResMsg_21002.Builder.class);
      }

      // Construct using xn.protobuf.test.TestMsg.TestResMsg_21002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xn.protobuf.test.TestMsg.internal_static_TestResMsg_21002_descriptor;
      }

      public xn.protobuf.test.TestMsg.TestResMsg_21002 getDefaultInstanceForType() {
        return xn.protobuf.test.TestMsg.TestResMsg_21002.getDefaultInstance();
      }

      public xn.protobuf.test.TestMsg.TestResMsg_21002 build() {
        xn.protobuf.test.TestMsg.TestResMsg_21002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xn.protobuf.test.TestMsg.TestResMsg_21002 buildPartial() {
        xn.protobuf.test.TestMsg.TestResMsg_21002 result = new xn.protobuf.test.TestMsg.TestResMsg_21002(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xn.protobuf.test.TestMsg.TestResMsg_21002) {
          return mergeFrom((xn.protobuf.test.TestMsg.TestResMsg_21002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xn.protobuf.test.TestMsg.TestResMsg_21002 other) {
        if (other == xn.protobuf.test.TestMsg.TestResMsg_21002.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xn.protobuf.test.TestMsg.TestResMsg_21002 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xn.protobuf.test.TestMsg.TestResMsg_21002) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TestResMsg_21002)
    }

    static {
      defaultInstance = new TestResMsg_21002(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TestResMsg_21002)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TestReqMsg_21001_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TestReqMsg_21001_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TestResMsg_21002_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TestResMsg_21002_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTestMsg.proto\032\017PlayerMsg.proto\"\022\n\020Test" +
      "ReqMsg_21001\"\022\n\020TestResMsg_21002B\024\n\020xn.p" +
      "rotobuf.testH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TestReqMsg_21001_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TestReqMsg_21001_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TestReqMsg_21001_descriptor,
              new java.lang.String[] { });
          internal_static_TestResMsg_21002_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_TestResMsg_21002_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TestResMsg_21002_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          xn.protobuf.player.PlayerMsg.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
